version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install cfn-lint

  build:
    # This should be moved to a shell script if it gets more complicated.
    commands:
      - set -e

      - BRANCH_NAME=${CODEBUILD_WEBHOOK_HEAD_REF#"refs/heads/"}
      - ARTIFACT_PATH=branch/$BRANCH_NAME/$CODEBUILD_BUILD_NUMBER

      - cd $CODEBUILD_SRC_DIR

      - echo "Validating Cloudformation Templates..."
      - cfn-lint cicd/1-setup/*.template.yml
      - cfn-lint cicd/2-cicd/*.template.yml
      - cfn-lint cicd/3-app/aiproxy/template.yml

      - echo "Running Unit Tests..."
      - python -m unittest test_app.py

      - echo "Building Docker Image..."
      - IMAGE_NAME=aiproxy
      - IMAGE_TAG=$(git rev-parse --short HEAD)
      - docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .

      - echo "Pushing Docker Image to ECR..."
      - echo "This is where I would push the docker image to ECR, when I get around to it"
