AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Provision an instance of the Javabuilder service. Empty the ContentBucket before deleting this Stack.
Parameters:
  BaseDomainName:
    Type: String
    Description: Base domain name (e.g. 'code.org' in 'aiproxy.code.org').
  # BaseDomainNameHostedZonedID:
  #   Type: String
  #   Description: AWS Route53 Hosted Zone ID for base domain name.
  SubdomainName:
    Type: String
    Description: Subdomain name for javabuilder service (e.g. 'javabuilder' in 'javabuilder.code.org').
  AppImageUri:
    Type: String
    Description: URI of the Docker image in ECR.

# Conditions:
#   IsDevCondition: !Equals [!Ref BaseDomainName, "dev-code.org"]

Resources:

  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Sub "${SubdomainName}.${BaseDomainName}."

  Domain:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Sub "${SubdomainName}.${BaseDomainName}"
      Type: A
      AliasTarget:
        DNSName: !GetAtt LoadBalancer.DNSName
        HostedZoneId: !GetAtt LoadBalancer.CanonicalHostedZoneID
  
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      SecurityGroups:
        - !ImportValue VPC-ELBSecurityGroup
      Subnets:
        # TODO: This copies geocoder, but we should probably have a separate subnet for this service.
        - !ImportValue VPC-SubnetB
        - !ImportValue VPC-SubnetC
      Scheme: internet-facing

  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ECSTargetGroup
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP

  ECSTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      # TODO: This copies geocoder, but we should probably have a separate VPC for this service.
      VpcId: !ImportValue VPC
      Port: 80
      TargetType: ip
      Protocol: HTTP
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2

  ECSCluster:
    Type: "AWS::ECS::Cluster"

  ECSService:
    Type: "AWS::ECS::Service"
    DependsOn: LoadBalancerListener
    Properties:
      Cluster: !Ref ECSCluster
      DesiredCount: 1
      LaunchType: FARGATE
      TaskDefinition: !Ref ECSTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups: 
            - !Ref ECSSecurityGroup
          Subnets:
            # TODO: This copies geocoder, but we should probably have a separate subnet for this service.
            - !ImportValue VPC-SubnetB
            - !ImportValue VPC-SubnetC
      LoadBalancers:
        - ContainerName: aiproxy
          ContainerPort: 80
          TargetGroupArn: !Ref ECSTargetGroup

  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Security Group for ECS Service
      # TODO: This copies geocoder, but we should probably have a separate VPC for this service.
      VpcId: !ImportValue VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  ECSTaskDefinition:
    Type: "AWS::ECS::TaskDefinition"
    Properties:
      Family: aiproxy
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc
      ExecutionRoleArn: !ImportValue AiProxyECSTaskExecutionRoleArn
      Cpu: 256
      Memory: 512
      ContainerDefinitions:
        - Name: aiproxy
          Image: !Ref AppImageUri
          Memory: 512
          Cpu: 256
          Essential: true
          PortMappings:
            - ContainerPort: 80
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "${AWS::StackName}"

Outputs:
  AiProxyURL:
    Value:
      !Ref Domain
