AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Provision an instance of the Javabuilder service. Empty the ContentBucket before deleting this Stack.
Parameters:
  BaseDomainName:
    Type: String
    Description: Base domain name (e.g. 'code.org' in 'javabuilder.code.org').
  # BaseDomainNameHostedZonedID:
  #   Type: String
  #   Description: AWS Route53 Hosted Zone ID for base domain name.
  SubdomainName:
    Type: String
    Description: Subdomain name for javabuilder service (e.g. 'javabuilder' in 'javabuilder.code.org').
  AppImageUri:
    Type: String
    Description: URI of the Docker image in ECR.

# Conditions:
#   IsDevCondition: !Equals [!Ref BaseDomainName, "dev-code.org"]

Resources:
  Domain:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub "${BaseDomainName}."
      Name: !Sub "${SubdomainName}.${BaseDomainName}"
      Type: A
      TTL: 300
      ResourceRecords:
      - 8.8.8.8

  ECSTaskDefinition:
    Type: "AWS::ECS::TaskDefinition"
    Properties:
      Family: ExampleFamily
      Cpu: '256'
      Memory: '512'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/ecsTaskExecutionRole
      ContainerDefinitions:
        - Name: ExampleContainer
          Image: !Ref AppImageUri
          Memory: 512
          Cpu: 256
          Essential: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref AWS::StackName
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs

Outputs:
  AiProxyURL:
    Value:
      !Ref Domain
